### ISSUE TITLE
defaultPageSize not respected in nested collection when setting size

### ISSUE THREAD

**Issue by joebalancio** [mio/mio#20]
This is a weird bug, I'll explain later when I get home.

**Comment by joebalancio** [comment]
Finally got around to putting together an example. The current collection is `configs` and the related collection is `items`. Below are the API responses (as gists) for a few calls

# Example 1
[GET /api/configs?withRelated[items][nested]=true](https://gist.github.com/joebalancio/3f13be551f27a5c21e27)
There should actually by over 50 `items` per `config`, but only 5 are returned. A total of 25 are returned in the response which is 5 per config for the first 5 configs.

# Example 2
[GET /api/configs?withRelated[items]=true](https://gist.github.com/joebalancio/9b8e3798fd2f6be5d50d)
The first 5 configs contains 20 items each which is incorrect. The last 5 configs should contain items, but are empty.

# Example 3
[GET /api/configs/553aa10e18b5922c08dbe816?withRelated[items][nested]=true](https://gist.github.com/joebalancio/7a9cb871ba4fcf86d25a)
Retrieving a single config returns all the items.

**Comment by alexmingoia** [comment]
I am closing this because it's an issue with mio-mongo and I've opened an issue in that repo.
