### ISSUE TITLE
Need total number of records in collection

### ISSUE THREAD

**Issue by joebalancio** [mio/mio#21]
In order to paginate correctly (calculate number of available pages), I need total number of records in a collection. Any suggestions on how to do this?

**Comment by alexmingoia** [comment]
Search instead of display a total number of pages :stuck_out_tongue:

A hook to count the number of documents:

```javascript
Resource.hook('collection:get', function (query, next) {
  this.options.mongo.dbCollection.count({...}, function (err, count) {
    query._total = count;
    next(err);
  });
});

**Comment by joebalancio** [comment]
To do pagination on the frontend using Backgrid, the API needs to return the total number of records. 

Thanks for the advice. Another idea is to update `MioMongoExec` in mio/mongo to use the existing cursor to return the count. I think this avoids another trip to the DB and it also hides the query details from the API. But this requires more changes such as updating Resource.Collection to accept a `total` argument. I'll stick with what you recommended above.

See:
http://mongodb.github.io/node-mongodb-native/1.4/api-generated/cursor.html#count
https://github.com/mio/mongo/blob/master/lib/mio-mongo.js#L1133

This is what the code would look like:
```js
    function MioMongoExec () {
      if (method === 'find') {
        var query = args[0];
        var options = args[1];
        var cursor = settings.dbCollection.find(query, options);

        // nested callbacks so that the count is accurate
        cursor.count(function (err, count) {
          ['sort', 'skip', 'limit'].forEach(function (filter) {
            if (options[filter]) {
              cursor[filter](options[filter]);
            }
          });
          cursor.toArray(function (err, items) {
            cb(err, items, count);
          });
        });
      } else {
        settings.dbCollection[method].apply(settings.dbCollection, args);
      }
    }
```

**Comment by alexmingoia** [comment]
This could be added but it would impact performance of queries that do not need the total, since instead of scanning only 100 or 200 or however many documents are in the page size, mongodb has to scan the entire collection. A better idea may be to expose a `count()` method on the query that adds the count method to the cursor and total to the resulting mio collection.

**Comment by alexmingoia** [comment]
maybe `withCount()` or `withTotal()`

**Comment by alexmingoia** [comment]
`Resource.Collection.get().where(...).withCount().exec(...)` ?

**Comment by alexmingoia** [comment]
I will add this.

**Comment by alexmingoia** [comment]
This is added in `mio@1.2.0` and `mio-mongo@0.11.0`.
