### ISSUE TITLE
Collection.prototype.put should send JSON in trigger

### ISSUE THREAD

**Issue by joebalancio** [mio/mio#23]
It should be inline with `Resource.prototype.put`.

https://github.com/mio/mio/blob/master/lib/collection.js#L502

I'll submit a PR.

**Comment by joebalancio** [comment]
Actually I misunderstood the functionality. I thought that when I called `.put()` on a instantiated collection that it would replace all existing items in the collection. But I think it's actually meant to replace all items returned by a query with a replacement doc.

**Comment by alexmingoia** [comment]
Ah. I see how that is confusing..
